### ISSUE TITLE
Get physical disks instead of virtual disks from raid controllers

### ISSUE THREAD

**Issue by dalehamel** [Shopify/genesis_collector#2]
Our collector is showing virtual disks like:

> 008817b21bd7d8881b00609cf760f681	223 GB	PERC H710P

Where we actually care more about the physical disks backing it.

We need to be able to recognize and dereference at least:

* Dell raid controllers
* megaraid raid controllers

Typically, we'll be running into LSI-based controllers.

There is probably some intelligent way for us to figure out whether a disk is physical or virtual.

**Comment by dalehamel** [comment]
I recommend we take this approach:

* Detect if it's a raid card or not based on a list of known raid cards, or some other logic (eg, lack of serial number, vendor, etc)
* Use MegaCLI to enumerate physical drives and adapters http://docs.ovh.ca/en/faqs-hdd-serial.html
* Use smartctl to get the serial numbers for the actual drives https://www.smartmontools.org/wiki/Supported_RAID-Controllers

Since we pretty much only use LSI raid cards, we should be able to detect them pretty easily. The kicker here is that we need to have:

* megacli (proprietary) installed on the system
* smartctl (FOSS) installed on the system

That shouldn't be a problem though, as any system with a RAID will have megacli on it somewhere, and we can install megacli on the intake image.

@dwradcliffe for thoughts

**Comment by dwradcliffe** [comment]
:+1:

**Comment by dwradcliffe** [comment]
I think we can simplify this, and get rid of lshw. Looks like smartctl can get us everything we need.
